import { readFile, mkdir, readdir, stat, unlink } from 'node:fs/promises'
import { basename, isAbsolute, join, relative, resolve } from 'node:path'
import { homedir } from 'node:os'
import type { Context } from '@deepseek-ai/cordis'
import { effectiveApprovalPolicy } from '@deepseek-ai/dsh-user-approval'
import type { ContentBlock } from '@deepseek-ai/dsh-llm'
import { defineTool, type JsonValue } from '@deepseek-ai/dsh-tools'
import type { ComputerUseConfig } from './config.ts'
import { DISABLED_MESSAGE } from './config.ts'
import * as desktop from './runtime.ts'

interface ToolDeps { ctx: Context; getConfig: () => ComputerUseConfig }
type Exec = { agent?: unknown; name: string; callId: unknown; signal: AbortSignal }
function json(value: object): JsonValue { return value as unknown as JsonValue }
function textOutput(text: string): ContentBlock[] { return [{ type: 'text', text }] }
function screenshotRoot(config: ComputerUseConfig): string {
  const root = resolve(process.env.DSH_HOME ?? join(homedir(), '.dsh'))
  if (isAbsolute(config.screenshotDir)) throw new Error('截图目录必须是 DSH home 下的相对路径')
  const target = resolve(root, config.screenshotDir)
  const outside = relative(root, target)
  if (outside === '..' || outside.startsWith('..\\') || outside.startsWith('../') || isAbsolute(outside)) throw new Error('截图目录不能离开 DSH home')
  return target
}
function screenshotPath(config: ComputerUseConfig, windowId: number): string { return join(screenshotRoot(config), `window-${windowId}-${Date.now()}.png`) }
/** Delete screenshots older than the retention window so the plugin does not
 * grow without bound in DSH home (privacy + disk hygiene). Best effort. */
async function pruneScreenshots(config: ComputerUseConfig): Promise<void> {
  const retention = config.screenshotRetention
  if (!retention || retention <= 0) return
  const dir = screenshotRoot(config)
  let entries: string[]
  try { entries = await readdir(dir) } catch { return }
  const cutoff = Date.now() - retention
  for (const name of entries) {
    if (!/^window-.*\.png$/.test(name)) continue
    try {
      const st = await stat(join(dir, name))
      if (st.mtimeMs < cutoff) await unlink(join(dir, name))
    } catch { /* best effort */ }
  }
}
const BROWSER_HINTS = ['firefox', 'msedge', 'chrome', 'edge', 'brave', 'opera', 'vivaldi']
function enabled(config: ComputerUseConfig): void { if (!config.enabled) throw new Error(DISABLED_MESSAGE); if (process.platform !== 'win32') throw new Error('dsh-computer-use 仅支持 Windows'); if (!config.allowControl) throw new Error('DSH 控制权限未开启：请打开聊天框旁“允许 DSH 控制电脑”的开关') }
function gate(deps: ToolDeps): void { const config = deps.getConfig(); enabled(config); desktop.configureOverlay(config) }
async function approve(ctx: Context, exec: Exec, config: ComputerUseConfig, reason: string): Promise<void> { if (!config.requireApproval || exec.agent === undefined) return; const agent = exec.agent as { session?: { events?: readonly unknown[] } }; const policy = effectiveApprovalPolicy((agent.session?.events ?? []) as never); if (policy === 'never') { if (config.skipApprovalWhenPolicyNever) return; throw new Error('当前会话审批策略为“不再询问”，此计算机控制操作被拒绝') } const outcome = await ctx.approval.request({ agent: agent as never, toolName: exec.name, callId: exec.callId as never, reason, signal: exec.signal }); if (outcome !== 'allowed-once') throw new Error('用户拒绝了此计算机控制操作') }
async function attach(ctx: Context, path: string): Promise<unknown> { const data = await readFile(path); return ctx.attachments.saveImage({ data: new Uint8Array(data), mediaType: 'image/png', name: basename(path) }) }
function failure(error: unknown): JsonValue { if (error instanceof desktop.ComputerUseError) return json(error.toJSON()); return json({ ok: false, code: 'ACTION_FAILED', recovery: 'RETRY', message: error instanceof Error ? error.message : String(error) }) }
async function action<T>(fn: () => Promise<T> | T): Promise<JsonValue> { try { return json(await fn() as object) } catch (error) { return failure(error) } }
function actionParams() { return { observationId: { type: 'string', required: true, description: '最近一次 computer_get_window_state 返回的 observationId' } } as const }
function validate(args: unknown): desktop.Observation { const v = args as { windowId?: number; observationId?: string }; if (typeof v.windowId !== 'number' || !Number.isInteger(v.windowId)) throw new Error('windowId 必须是整数'); if (typeof v.observationId !== 'string') throw new Error('observationId 必须是字符串'); return desktop.validateObservation(v.observationId, v.windowId, 'action') }

export function defineListWindowsTool(deps: ToolDeps) { return defineTool({ name: 'computer_list_apps', description: '列出当前 Windows 桌面窗口。', parameters: {}, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 60_000, isConcurrencySafe: () => false, async execute() { gate(deps); desktop.showOverlay(); return json({ windows: desktop.listWindows() }) } }) }
export function defineGetWindowStateTool(deps: ToolDeps) { return defineTool({ name: 'computer_get_window_state', description: '获取目标窗口的截图（只截该窗口，不泄露其他窗口）和 Windows UI Automation 观察结果。截图左上角是坐标原点；坐标按窗口相对处理，动作必须使用本次返回的 observationId。', parameters: { windowId: { type: 'number', required: true }, includeScreenshot: { type: 'boolean' }, includeText: { type: 'boolean' } }, output: { schema: { type: 'json' } as const, render: (_a, value) => { const v = value as { screenshotAttachment?: unknown }; const blocks: ContentBlock[] = []; if (v.screenshotAttachment !== undefined) blocks.push({ type: 'image', attachment: v.screenshotAttachment } as unknown as ContentBlock); blocks.push({ type: 'text', text: JSON.stringify(value) }); return blocks } }, timeoutMs: 180_000, isConcurrencySafe: () => false, async execute(args) { gate(deps); const id = (args as { windowId?: number }).windowId; if (typeof id !== 'number' || !Number.isInteger(id)) throw new Error('windowId 必须是整数'); return action(async () => { const current = desktop.assertSafeWindow(id, '观察'); const state: desktop.WindowState = { ...current }; if ((args as { includeScreenshot?: boolean }).includeScreenshot !== false) { const path = screenshotPath(deps.getConfig(), id); await mkdir(screenshotRoot(deps.getConfig()), { recursive: true }); const capture = desktop.capture(id, path); state.screenshotPath = capture.path; state.screenshotRect = capture.rect; state.coordinateSpace = 'screenshot'; await pruneScreenshots(deps.getConfig()) } if ((args as { includeText?: boolean }).includeText !== false) { const tree = desktop.accessibilityTree(id); state.accessibilityTree = tree.nodes; state.uiaChecksum = tree.checksum; state.uiaChecksumMode = tree.mode; state.uiaTruncated = tree.truncated } const observation = desktop.createObservation(id, state); const value: Record<string, unknown> = { ...observation }; if (state.screenshotPath) value.screenshotAttachment = await attach(deps.ctx, state.screenshotPath); return value }) } }) }
export function defineActivateWindowTool(deps: ToolDeps) { return defineTool({ name: 'computer_activate_window', description: '激活指定窗口。', parameters: { windowId: { type: 'number', required: true } }, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 60_000, isConcurrencySafe: () => false, async execute(args) { gate(deps); const id = (args as { windowId?: number }).windowId; if (typeof id !== 'number') throw new Error('windowId 必须是数字'); return action(() => desktop.activate(id)) } }) }
export function defineClickTool(deps: ToolDeps) { return defineTool({ name: 'computer_click', description: '在最新 observation 对应窗口内点击：传 elementIndex 触发 UIA 元素级点击，或传 x/y 窗口相对坐标点击。', parameters: { windowId: { type: 'number', required: true }, ...actionParams(), elementIndex: { type: 'number', description: 'UI 树中的元素索引（与 x/y 二选一，优先）' }, x: { type: 'number', description: '窗口相对横坐标' }, y: { type: 'number', description: '窗口相对纵坐标' }, coordinateSpace: { type: 'string', enum: ['auto', 'screenshot', 'screen', 'window'], description: '坐标系，默认 auto' }, mouseButton: { type: 'string', enum: ['left', 'middle', 'right'] }, clickCount: { type: 'number' }, clickMethod: { type: 'string', enum: ['auto', 'post'], description: 'auto=前台真实鼠标点击；post=后台消息点击，默认 auto' } }, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 120_000, isConcurrencySafe: () => false, async execute(args, exec) { gate(deps); desktop.showOverlay((args as { windowId?: number }).windowId ?? 0); await approve(deps.ctx, exec, deps.getConfig(), '模拟鼠标点击'); return action(() => { const v = args as any; const observation = validate(v); const button = v.mouseButton ?? 'left'; if (!['left', 'middle', 'right'].includes(button)) throw new Error('鼠标按钮无效'); const options: desktop.ClickOptions = {}; if (v.elementIndex !== undefined) options.elementIndex = v.elementIndex; if (v.clickMethod !== undefined) options.clickMethod = v.clickMethod; return desktop.click(v.windowId, v.x ?? 0, v.y ?? 0, button, v.clickCount ?? 1, observation, v.coordinateSpace ?? 'auto', options) }) } }) }
export function defineTypeTextTool(deps: ToolDeps) { return defineTool({ name: 'computer_type_text', description: '向最新 observation 对应窗口输入 Unicode 文本。', parameters: { windowId: { type: 'number', required: true }, ...actionParams(), text: { type: 'string', required: true } }, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 120_000, isConcurrencySafe: () => false, async execute(args, exec) { gate(deps); desktop.showOverlay((args as { windowId?: number }).windowId ?? 0); const v = args as any; await approve(deps.ctx, exec, deps.getConfig(), `输入文本（${String(v.text).length} 字符）`); return action(() => { validate(v); return desktop.typeText(v.windowId, v.text) }) } }) }
export function definePressKeyTool(deps: ToolDeps) { return defineTool({ name: 'computer_press_key', description: '发送不包含 Windows/Meta 键的按键。', parameters: { windowId: { type: 'number', required: true }, ...actionParams(), key: { type: 'string', required: true } }, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 120_000, isConcurrencySafe: () => false, async execute(args, exec) { gate(deps); desktop.showOverlay((args as { windowId?: number }).windowId ?? 0); const v = args as any; await approve(deps.ctx, exec, deps.getConfig(), `发送按键 ${v.key}`); return action(() => { validate(v); return desktop.pressKey(v.windowId, v.key) }) } }) }
export function defineScrollTool(deps: ToolDeps) { return defineTool({ name: 'computer_scroll', description: '在窗口内滚动：传 elementIndex 则在该元素中心滚动，否则在 x/y 窗口相对坐标处滚动。', parameters: { windowId: { type: 'number', required: true }, ...actionParams(), elementIndex: { type: 'number', description: 'UI 树中的元素索引（与 x/y 二选一，优先）' }, x: { type: 'number', description: '窗口相对横坐标' }, y: { type: 'number', description: '窗口相对纵坐标' }, coordinateSpace: { type: 'string', enum: ['auto', 'screenshot', 'screen', 'window'], description: '坐标系，默认 auto' }, scrollX: { type: 'number' }, scrollY: { type: 'number' } }, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 120_000, isConcurrencySafe: () => false, async execute(args, exec) { gate(deps); desktop.showOverlay((args as { windowId?: number }).windowId ?? 0); await approve(deps.ctx, exec, deps.getConfig(), '模拟滚动'); return action(() => { const v = args as any; const observation = validate(v); const options: desktop.ScrollOptions = {}; if (v.elementIndex !== undefined) options.elementIndex = v.elementIndex; return desktop.scroll(v.windowId, v.x ?? 0, v.y ?? 0, v.scrollX ?? 0, v.scrollY ?? 0, observation, v.coordinateSpace ?? 'auto', options) }) } }) }
export function defineDragTool(deps: ToolDeps) { return defineTool({ name: 'computer_drag', description: '在窗口内拖动：可用元素索引或窗口相对坐标指定起点/终点。', parameters: { windowId: { type: 'number', required: true }, ...actionParams(), fromElementIndex: { type: 'number', description: '起点元素索引（与 fromX/fromY 二选一，优先）' }, toElementIndex: { type: 'number', description: '终点元素索引（与 toX/toY 二选一，优先）' }, fromX: { type: 'number', description: '起点窗口相对横坐标' }, fromY: { type: 'number', description: '起点窗口相对纵坐标' }, toX: { type: 'number', description: '终点窗口相对横坐标' }, toY: { type: 'number', description: '终点窗口相对纵坐标' }, coordinateSpace: { type: 'string', enum: ['auto', 'screenshot', 'screen', 'window'], description: '坐标系，默认 auto' } }, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 120_000, isConcurrencySafe: () => false, async execute(args, exec) { gate(deps); desktop.showOverlay((args as { windowId?: number }).windowId ?? 0); await approve(deps.ctx, exec, deps.getConfig(), '模拟拖动'); return action(() => { const v = args as any; const observation = validate(v); const options: desktop.DragOptions = {}; if (v.fromElementIndex !== undefined) options.fromElementIndex = v.fromElementIndex; if (v.toElementIndex !== undefined) options.toElementIndex = v.toElementIndex; return desktop.drag(v.windowId, v.fromX ?? 0, v.fromY ?? 0, v.toX ?? 0, v.toY ?? 0, observation, v.coordinateSpace ?? 'auto', options) }) } }) }
export function defineLaunchAppTool(deps: ToolDeps) { return defineTool({ name: 'computer_launch_app', description: '启动应用；启动浏览器时强制 --new-window 保证新开窗口、绝不覆盖 DSH 聊天窗；启动成功不代表已经获得可操作窗口，必须重新观察。', parameters: { app: { type: 'string', required: true }, args: { type: 'array', items: { type: 'string' } } }, output: { schema: { type: 'json' } as const, render: (_a, v) => textOutput(JSON.stringify(v)) }, timeoutMs: 60_000, isConcurrencySafe: () => false, async execute(args, exec) { gate(deps); desktop.showOverlay(); const v = args as any; await approve(deps.ctx, exec, deps.getConfig(), `启动应用 ${v.app}`); return action(async () => { const { spawn } = await import('node:child_process'); const app = String(v.app).trim(); if (!app || app.includes('..')) throw new desktop.ComputerUseError('UNSAFE_APP', '应用路径不安全', 'DENY'); const launchArgs: string[] = Array.isArray(v.args) ? v.args.map(String) : []; const appLower = app.toLowerCase(); const isBrowser = BROWSER_HINTS.some((h) => appLower.includes(h)); let forcedNewWindow = false; if (isBrowser && !launchArgs.some((a) => ['--new-window', '-new-window'].includes(a.toLowerCase()))) { launchArgs.unshift('--new-window'); forcedNewWindow = true } const child = spawn(app, launchArgs, { detached: true, stdio: 'ignore', windowsHide: true })
      child.unref()
      // A missing/unrunnable target emits an async 'error' event (ENOENT etc.).
      // Resolve the launch race: 'spawn' = created, 'error' = failed. The
      // listener also guarantees the error never becomes an uncaught exception.
      const started = await new Promise<boolean>((resolve) => {
        child.once('spawn', () => resolve(true))
        child.once('error', () => resolve(false))
      })
      if (!started) throw new desktop.ComputerUseError('NATIVE_LAUNCH_FAILED', '应用启动失败，请确认路径或应用名正确', 'NONE')
      return { launched: app, args: launchArgs, forcedNewWindow, requiresObservation: true } }) } }) }
export function disposeRuntime(): void { desktop.disposeRuntime() }
export function stopControlSession(): void { desktop.stopControlSession() }
